name: Build OpenWrt for RK3229 (ARMv7)

on:
  workflow_dispatch:
    inputs:
      kernel_version:
        description: 'Kernel version (6.6 or 6.12)'
        required: true
        default: '6.6'
        type: choice
        options:
        - '6.6'
        - '6.12'
  push:
    branches: [rk3229]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 180

    steps:
      - name: Checkout kode
        uses: actions/checkout@v4
        with:
          repository: pitekkate/openwrt-rk3229-box
          ref: rk3229
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential clang flex bison g++ gawk gcc-multilib g++-multilib gettext git libncurses5-dev libssl-dev python3-distutils rsync unzip zlib1g-dev file wget

      - name: Setup build environment
        run: |
          echo "FORCE_UNSAFE_CONFIGURE=1" >> $GITHUB_ENV
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Configure for RK3229 (ARMv7)
        run: |
          echo "CONFIG_TARGET_rockchip=y" > .config
          echo "CONFIG_TARGET_rockchip_armv7=y" >> .config
          echo "CONFIG_TARGET_rockchip_armv7_DEVICE_rk3229-box=y" >> .config
          
          if [ "${{ github.event.inputs.kernel_version }}" == "6.12" ]; then
            echo "CONFIG_LINUX_6_12=y" >> .config
          else
            echo "CONFIG_LINUX_6_6=y" >> .config
          fi
          
          make defconfig

      - name: Apply kernel-specific configuration
        run: |
          KERNEL_VERSION="${{ github.event.inputs.kernel_version || '6.6' }}"
          CONFIG_FILE="target/linux/rockchip/armv7/config-$KERNEL_VERSION"
          
          if [ -f "$CONFIG_FILE" ]; then
            echo "Applying kernel $KERNEL_VERSION configuration"
            cat "$CONFIG_FILE" >> .config
            make defconfig
          else
            echo "Error: Kernel config $CONFIG_FILE not found!"
            exit 1
          fi

      - name: Build firmware
        run: make -j$(($(nproc) + 1)) V=s

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: openwrt-rk3229-firmware-${{ github.event.inputs.kernel_version || '6.6' }}
          path: |
            bin/targets/rockchip/armv7/*.img.gz
            bin/targets/rockchip/armv7/*.manifest
