name: OpenWrt RK3229 Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install build dependencies
      run: |
        sudo apt update
        sudo apt install -y \
          binutils \
          bzip2 \
          diffutils \
          findutils \
          flex \
          gawk \
          gcc \
          g++ \
          git \
          util-linux \
          grep \
          libc6-dev \
          zlib1g-dev \
          make \
          perl \
          python3 \
          python3-distutils \
          python3-pyelftools \
          python3-netifaces \
          libcrypt-dev \
          rsync \
          subversion \
          unzip \
          which \
          jq

    - name: Setup environment
      run: |
        echo "CONFIG_TARGET_rockchip=y" > .config
        echo "CONFIG_TARGET_rockchip_armv7=y" >> .config
        echo "CONFIG_TARGET_rockchip_armv7_DEVICE_rockchip_rk3229-box=y" >> .config
        echo "CONFIG_LUCI_LANG_en=y" >> .config
        echo "CONFIG_LUCI_LANG_zh-cn=y" >> .config

    - name: Prepare configuration
      run: |
        make defconfig
        ./scripts/diffconfig.sh > diffconfig
        cat diffconfig

    - name: Build OpenWrt
      run: |
        make -j$(($(nproc) + 1)) V=s

    - name: Upload artifacts
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: openwrt-rockchip-rk3229-binaries
        path: |
          bin/targets/rockchip/armv7/*
          !bin/targets/**/*.buildinfo
          !bin/targets/**/*.manifest
          !bin/targets/**/*.json
        retention-days: 7

    - name: Upload build logs on failure
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: build-failure-logs
        path: |
          logs/
          .config
          diffconfig
        retention-days: 7
